- step:
    name: Train Iris Model
    image: python:3.12
    command:
      - cd tasks
      - pip install -r requirements.txt
      - python train.py {parameters}
    inputs:
      - name: iris_dataset
        optional: false
    parameters:
      - name: epochs
        type: integer
        default: 1
        description: Number of epochs for training
      - name: learning_rate
        type: float
        default: 0.001
        description: Learning rate for training
      - name: batch_size
        type: integer
        default: 32
        description: Batch size for training


- task:
    step: Train Iris Model
    name: train-iris
    type: RANDOM-SEARCH
    maximum-queued-executions: 100
    execution-count: 10
    on-child-error: stop_all-AND_error
    reuse-children: true
    parameters:
      - name: epochs
        style: linear
        rules:
          end: 100
          start: 100
          step: 100
        
      - name: learning_rate
        style: linear
        rules:
          end: 0.9
          start: 0.1
          step: 0.1

      - name: batch_size
        style: multiple
        rules:
          items: [16, 32, 64, 128]